name: SnappyMail
version: "1.0.3"
slug: snappymail
description: Simple, modern & fast web-based email client. Supports multiple accounts including Gmail.
url: https://github.com/gregorwolf1973/snappymail-addon
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_port: 8889
panel_icon: mdi:email
panel_title: SnappyMail
homeassistant_api: false
options:
  admin_password: "changeme"
  upload_max_size: "25M"
  memory_limit: "128M"
  log_to_stdout: false
schema:
  admin_password: str
  upload_max_size: str
  memory_limit: str
  log_to_stdout: bool
map:
  - type: addon_config
    read_only: false
image: ghcr.io/gregorwolf1973/snappymail-addon/snappymail/{arch}
