server {
    listen 8889 default_server;
    server_name _;

    root /var/www/snappymail;
    index index.php;

    client_max_body_size 25M;
    absolute_redirect off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~ ^/data/ {
        deny all;
    }

    access_log /proc/1/fd/1;
    error_log /proc/1/fd/2;
}
